#预上线环境
server:
  port: 9000

spring:
  application:
    name: authentication-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tcq-19961020.mysql.rds.aliyuncs.com/testcode?useUnicode=true&characterEncodeing=utf-8&useSSL=false&serverTimezone=UTC
    username: tanyongxing
    password: As782310197


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    #    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 单个文件的最大值
      max-request-size: 100MB # 上传文件总的最大值
  main:
    allow-bean-definition-overriding: true



  jackson:
    serialization:
      fail-on-empty-beans: false
file:
  path: ./upload/ #图片上传的存放路径x
#  path: E:/upload/ #图片上传的存放路径x

img:
  imgWidth: 800
  imgHeight: 502

